# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Install the hls-proxy package globally
RUN npm install --global "@warren-bank/hls-proxy"

# Expose the port that hlsd will run on
EXPOSE 8080

# Command to start the hlsd server
CMD ["hlsd","--host", "0.0.0.0", "--port", "8080"]
