services:
  bajag-theater:
    container_name: theater-container
    image: theater:latest # Replace with the name of the Docker image for the Express app
    build:
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    volumes:
      - ${REPLAY_DIR}:/app/replay
      - ${PWD}/cookies:/app/cookies
      - ${PWD}/video:/app/video
    env_file:
      - .env
    restart: always
